### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by conman0552** [evaera/RoVer#262] opened 2020-05-07 00:35 UTC
Greetings. Today I recently set this up to use on several discord servers, seeing as the free tier of RoVer is unreliable due to various reasons. It ran fine, but I've been hitting bumps when attempting to bind ranks.
![image](https://user-images.githubusercontent.com/24281023/81241695-a1dff500-8fd0-11ea-8d93-1213b68c72dc.png)

I am running on a CentOS8 system and have set this up to run as a system process so that when it goes offline it will automatically restart.

What might be causing this issue of the bot locking up when I attempt to bind roles?

**Comment by conman0552** [comment] 2020-05-07 00:49
Ended up circumventing the problem by listing out all the arguments in 1 command, rather than using the step by step approach that expired in 30 seconds. Still an issue though for people who don't know how to read the documentation.

**Comment by mrwilyt** [comment] 2020-05-07 00:58
Are you trying to self host?

**Comment by conman0552** [comment] 2020-05-07 13:27
I am self-hosting. The bot runs, but certain commands such as !bind (nothing after that) cause this unhandled rejection to appear. Other than that it's running very well. Been running for a little over 24 hours now with no issues other than this.

**Comment by ElliottLMz** [comment] 2020-05-07 13:55
We do not provide support for self-hosting.

**Comment by conman0552** [comment] 2020-05-07 14:04
My issue isn't with the self hosting. If you read the original post I'm trying to point out that I'm under the pretense that there is a bug in the code (or one of the modules it relies on possibly?) that is causing the unhandled rejection error...

**Comment by chasegolem** [comment] 2020-05-13 23:19
Getting this error too and the bot won't even start, worked perfectly before and I haven't edited any of the code.

**Comment by evaera** [comment] 2020-05-13 23:23
There must be a problem with your environment then, because the code obviously works on our official versions of the bot.

Closing now as I can't reproduce this error

**Closed by evaera** 2020-05-13 23:23 UTC
