### ISSUE TITLE
Highly inappropriate

### ISSUE THREAD

**Issue by somebody12321** [evaera/RoVer#254] opened 2020-04-14 22:02 UTC
Hi so when I verified, the bot sent me something highly inappropriate. It said porn pussy + dick penis = baby egg and that is unacceptable. Don’t use this bot. Can get hacked easy.

This was in MY SERVER

**Comment by evaera** [comment] 2020-04-14 22:03
Spam dupe of #252

**Closed** 2020-04-14 22:02 UTC
Labels: invalid
