### ISSUE TITLE
Unbinding Trouble

### ISSUE THREAD

**Issue by coolguzman11** [evaera/RoVer#226] opened 2019-11-15 22:39 UTC
any help with unbinding a deleted role?

https://cdn.discordapp.com/attachments/373935421362536477/645027068270346270/unknown.png
https://cdn.discordapp.com/attachments/373935421362536477/645027102390747137/unknown.png

Luke Sky walkerToday at 4:29 PM
you can try !unbind <&IDHERE>
 
coolguzman11Today at 4:30 PM
unsuccessful
https://cdn.discordapp.com/attachments/425800792679645206/645027752633827329/unknown.png
and it still pops up on bindings, and is taking up space for a binding.

**Comment by OverHash** [comment] 2019-11-15 22:44
This is because you deleted the role before unbinding. Please re-create the role in Discord (with the correct name), then run the command
```
!Unbind <exact role name>
```
Then you can delete the role again.

For future reference, unbind before deleting a role

**Comment by OverHash** [comment] 2019-11-15 22:50
> This is because you deleted the role before unbinding. Please re-create the role in Discord (with the correct name), bind the new role to the old group stuff, then run the command
> 
> ```
> !Unbind <exact role name>
> ```
> 
> Then you can delete the role again.
> 
> For future reference, unbind before deleting a role

I was wrong, this is a problem with RoVer (although you shouldn't have deleted the role before unbinding).

Screenshots demonstrating this behaviour:
https://cdn.discordapp.com/attachments/425800792679645206/645032300727369733/unknown.png
https://cdn.discordapp.com/attachments/425800792679645206/645032353474805760/unknown.png

Steps to reproduce:
1 - Invite RoVer to server
2 - Create role
3 - Bind the role to a group
4 - Delete the role in Discord
You can no longer unbind the role, leaving it stuck with your bindings.

**Comment by PhoenixShay** [comment] 2019-11-23 23:07
Resolved in https://github.com/evaera/RoVer/commit/cdcc8167233a58d1b907975cfbd157a44aadfb35

**Closed by PhoenixShay** 2019-11-23 23:07 UTC
Labels: bug
